import type { User, Connection, Conversation } from './types';

export const users: User[] = [
  {
    id: '1',
    slug: 'alex-morgan',
    name: 'Alex Morgan',
    avatarUrl: 'https://picsum.photos/seed/user1/200/200',
    email: 'alex.morgan@example.com',
    role: 'Mentor',
    title: 'Senior Software Engineer at TechCorp',
    bio: '10+ years of experience in full-stack development, specializing in React and Node.js. Passionate about helping new developers grow their careers.',
    industry: 'Software Engineering',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'System Design'],
    goals: ['Career Growth', 'Technical Skills', 'Leadership'],
    experience: '10+ years',
    location: 'San Francisco, CA',
    availability: 'Weekdays after 6 PM PT',
    rating: 4.9,
  },
  {
    id: '2',
    slug: 'jordan-lee',
    name: 'Jordan Lee',
    avatarUrl: 'https://picsum.photos/seed/user2/200/200',
    email: 'jordan.lee@example.com',
    role: 'Mentee',
    title: 'Aspiring Product Manager',
    bio: 'Recent computer science graduate transitioning into product management. Eager to learn about product strategy, user research, and market analysis.',
    industry: 'Product Management',
    skills: ['Agile', 'JIRA', 'SQL', 'Python'],
    goals: ['Find first PM role', 'Learn product lifecycle', 'Improve communication'],
    experience: '< 1 year',
    location: 'New York, NY',
    availability: 'Flexible',
    rating: 4.5,
  },
  {
    id: '3',
    slug: 'casey-smith',
    name: 'Casey Smith',
    avatarUrl: 'https://picsum.photos/seed/user3/200/200',
    email: 'casey.smith@example.com',
    role: 'Both',
    title: 'UX/UI Designer at DesignFirm',
    bio: 'Creative designer with 5 years of experience in mobile and web app design. Looking to mentor junior designers and also connect with a senior leader for my own career growth.',
    industry: 'UX/UI Design',
    skills: ['Figma', 'Sketch', 'User Research', 'Prototyping', 'Design Systems'],
    goals: ['Mentor junior designers', 'Transition to a lead role'],
    experience: '5 years',
    location: 'London, UK',
    availability: 'Weekends',
    rating: 4.8,
  },
  {
    id: '4',
    slug: 'morgan-chen',
    name: 'Morgan Chen',
    avatarUrl: 'https://picsum.photos/seed/user4/200/200',
    email: 'morgan.chen@example.com',
    role: 'Mentor',
    title: 'Data Science Lead at DataDriven Inc.',
    bio: 'Passionate about data and machine learning. My expertise lies in building scalable ML models and leading data teams. I enjoy demystifying data science for newcomers.',
    industry: 'Data Science',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'Data Visualization', 'Big Data'],
    goals: ['Guide aspiring data scientists', 'Share industry knowledge'],
    experience: '8 years',
    location: 'Austin, TX',
    availability: 'Flexible',
    rating: 5.0,
  },
  {
    id: '5',
    slug: 'riley-jones',
    name: 'Riley Jones',
    avatarUrl: 'https://picsum.photos/seed/user5/200/200',
    email: 'riley.jones@example.com',
    role: 'Mentee',
    title: 'Marketing Student',
    bio: 'Final year marketing student with a focus on digital marketing. I have internship experience in SEO and content creation, and I am seeking guidance on starting a career in a fast-paced tech company.',
    industry: 'Digital Marketing',
    skills: ['SEO', 'Content Marketing', 'Google Analytics', 'Social Media'],
    goals: ['Secure a full-time marketing role', 'Network with professionals', 'Learn PPC advertising'],
    experience: '1 year (internships)',
    location: 'Chicago, IL',
    availability: 'Tuesdays and Thursdays',
    rating: 4.6,
  },
  {
    id: '6',
    slug: 'pat-taylor',
    name: 'Pat Taylor',
    avatarUrl: 'https://picsum.photos/seed/user6/200/200',
    email: 'pat.taylor@example.com',
    role: 'Mentor',
    title: 'Cybersecurity Consultant',
    bio: 'Certified cybersecurity expert with a background in network security and ethical hacking. I believe in a proactive approach to security and enjoy sharing my knowledge to help build a safer digital world.',
    industry: 'Cybersecurity',
    skills: ['Network Security', 'Penetration Testing', 'Cryptography', 'CISSP'],
    goals: ['Mentor on security best practices', 'Help with certification paths'],
    experience: '12 years',
    location: 'Remote',
    availability: 'Bi-weekly, evenings',
    rating: 4.9,
  },
];

export const currentUser: User = users[1]; // Jordan Lee is the logged-in user

export const connections: Connection[] = [
  { id: 'conn1', userId: '1', status: 'accepted', type: 'mentor' },
  { id: 'conn2', userId: '3', status: 'pending', type: 'mentee' },
  { id: 'conn3', userId: '4', status: 'accepted', type: 'mentor' },
];

export const conversations: Conversation[] = [
    {
      id: 'conv1',
      userId: '1',
      userName: 'Alex Morgan',
      userAvatar: 'https://picsum.photos/seed/user1/200/200',
      lastMessage: 'Great! Let\'s schedule a call for next week to discuss your resume.',
      lastMessageTimestamp: '2d',
      unreadCount: 0,
    },
    {
      id: 'conv2',
      userId: '4',
      userName: 'Morgan Chen',
      userAvatar: 'https://picsum.photos/seed/user4/200/200',
      lastMessage: 'Here\'s the article I mentioned about MLOps.',
      lastMessageTimestamp: '1d',
      unreadCount: 2,
    },
    {
        id: 'conv3',
        userId: '3',
        userName: 'Casey Smith',
        userAvatar: 'https://picsum.photos/seed/user3/200/200',
        lastMessage: 'Thanks for connecting!',
        lastMessageTimestamp: '5d',
        unreadCount: 0,
    },
];

export const findUserBySlug = (slug: string) => users.find(u => u.slug === slug);
export const findUserById = (id: string) => users.find(u => u.id === id);
